# Form implementation generated from reading ui file 'c:\Users\Moritz\Desktop\Gregtech Control Panel\main.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 674)
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"    font: \'Arial\';\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #dddddd;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2e2e2e;\n"
"    color: #ffffff;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3a3a3a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #505050;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"    selection-background-color: #5B86E5;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2b2b2b;\n"
"    selection-background-color: #5B86E5;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"#frame, #frame2, #frame3 {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"    border: 4px solid #444;\n"
"    border-radius: 0px;\n"
"}\n"
"")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 280, 661, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setLineWidth(4)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 641, 331))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.reac_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.reac_layout.setContentsMargins(0, 0, 0, 0)
        self.reac_layout.setObjectName("reac_layout")
        self.stats_container = QtWidgets.QVBoxLayout()
        self.stats_container.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.stats_container.setContentsMargins(-1, 10, -1, -1)
        self.stats_container.setObjectName("stats_container")
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.stats_container.addWidget(self.label_5)
        self.reac_activity_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reac_activity_label.sizePolicy().hasHeightForWidth())
        self.reac_activity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.reac_activity_label.setFont(font)
        self.reac_activity_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.reac_activity_label.setObjectName("reac_activity_label")
        self.stats_container.addWidget(self.reac_activity_label)
        self.fuel_rod_name = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuel_rod_name.sizePolicy().hasHeightForWidth())
        self.fuel_rod_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.fuel_rod_name.setFont(font)
        self.fuel_rod_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fuel_rod_name.setObjectName("fuel_rod_name")
        self.stats_container.addWidget(self.fuel_rod_name)
        self.stats_container.setStretch(0, 2)
        self.stats_container.setStretch(1, 1)
        self.reac_layout.addLayout(self.stats_container)
        self.line = QtWidgets.QFrame(parent=self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.reac_layout.addWidget(self.line)
        self.fuel_rod_container = QtWidgets.QGridLayout()
        self.fuel_rod_container.setObjectName("fuel_rod_container")
        self.reac_layout.addLayout(self.fuel_rod_container)
        self.reac_layout.setStretch(0, 1)
        self.reac_layout.setStretch(2, 3)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 661, 261))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setLineWidth(4)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 641, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.LapoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.LapoLayout.setContentsMargins(0, 0, 0, 0)
        self.LapoLayout.setObjectName("LapoLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.LapoLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.LapoLayout.addWidget(self.label_4)
        self.eu_stored = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.eu_stored.setFont(font)
        self.eu_stored.setText("")
        self.eu_stored.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.eu_stored.setObjectName("eu_stored")
        self.LapoLayout.addWidget(self.eu_stored)
        self.capacitorPercent = QtWidgets.QProgressBar(parent=self.verticalLayoutWidget)
        self.capacitorPercent.setStyleSheet("QProgressBar {\n"
"    background-color: #2c2f36;        /* dunkler Hintergrund */\n"
"    border: none;\n"
"    text-align: center;\n"
"    height: 24px;\n"
"    color: #ffffff;\n"
"    font: bold 10pt \'Segoe UI\';\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 0,\n"
"        stop: 0 #5B86E5,\n"
"        stop: 1 #A56DFF\n"
"    );\n"
"    margin: 0px;\n"
"}")
        self.capacitorPercent.setProperty("value", 24)
        self.capacitorPercent.setObjectName("capacitorPercent")
        self.LapoLayout.addWidget(self.capacitorPercent)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.EU_IN = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.EU_IN.setFont(font)
        self.EU_IN.setStyleSheet("color: green;")
        self.EU_IN.setText("")
        self.EU_IN.setObjectName("EU_IN")
        self.gridLayout.addWidget(self.EU_IN, 0, 1, 1, 1)
        self.EU_OUT = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.EU_OUT.setFont(font)
        self.EU_OUT.setStyleSheet("color: red;")
        self.EU_OUT.setText("")
        self.EU_OUT.setObjectName("EU_OUT")
        self.gridLayout.addWidget(self.EU_OUT, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.LapoLayout.addLayout(self.gridLayout)
        self.LapoLayout.setStretch(0, 2)
        self.LapoLayout.setStretch(1, 1)
        self.LapoLayout.setStretch(2, 1)
        self.LapoLayout.setStretch(3, 1)
        self.LapoLayout.setStretch(4, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(680, 10, 521, 201))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setLineWidth(4)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 501, 185))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.line_2 = QtWidgets.QFrame(parent=self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.redstone_list_view = QtWidgets.QListView(parent=self.verticalLayoutWidget_3)
        self.redstone_list_view.setObjectName("redstone_list_view")
        self.verticalLayout.addWidget(self.redstone_list_view)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Fluid Nuclear Reactor"))
        self.reac_activity_label.setText(_translate("MainWindow", "Not Running"))
        self.fuel_rod_name.setText(_translate("MainWindow", "Fuel Rod Type"))
        self.label.setText(_translate("MainWindow", "Lapotronic Super Capacitor"))
        self.label_4.setText(_translate("MainWindow", "EU Stored:"))
        self.capacitorPercent.setFormat(_translate("MainWindow", "%p%"))
        self.label_2.setText(_translate("MainWindow", "EU IN:"))
        self.label_3.setText(_translate("MainWindow", "EU OUT:"))
        self.label_6.setText(_translate("MainWindow", "Maintenance Issues"))
